# Generated by Django 3.2 on 2021-04-16 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='question',
            field=models.TextField(),
        ),
    ]
